import React,{useEffect,useMemo,useState} from "react";
import {Link} from "react-router-dom";
import {onAuthStateChanged,signInWithEmailAndPassword,signOut} from "firebase/auth";
import {collection,getDocs,query,orderBy} from "firebase/firestore";
import {auth,db} from "../firebase";
import {defaultCMS,loadCMS,loadRemoteCMS,saveRemoteCMS,resetCMS} from "./cms";
import "./Admin.css";

const clone=x=>JSON.parse(JSON.stringify(x));
const empty={name:"",phone:"",service:"",message:""};

export default function MrSabKuchAdmin(){
 const [user,setUser]=useState(null); const [authLoading,setAuthLoading]=useState(true); const [email,setEmail]=useState("technologiesniss@gmail.com"); const [password,setPassword]=useState(""); const [authMsg,setAuthMsg]=useState("");
 const [data,setData]=useState(()=>clone(loadCMS())); const [msg,setMsg]=useState(""); const [active,setActive]=useState("overview"); const [leads,setLeads]=useState([]); const [loadingLeads,setLoadingLeads]=useState(false);
 useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u);setAuthLoading(false);if(u)loadRemoteCMS().then(setData)}),[]);
 const updateBrand=(k,v)=>setData(d=>({...d,brand:{...d.brand,[k]:v}}));
 const updateList=(key,id,field,value)=>setData(d=>({...d,[key]:d[key].map(x=>x.id===id?{...x,[field]:value}:x)}));
 const add=(key,item)=>setData(d=>({...d,[key]:[...(d[key]||[]),item]}));
 const remove=(key,id)=>setData(d=>({...d,[key]:d[key].filter(x=>x.id!==id)}));
 const save=async()=>{try{await saveRemoteCMS(data);setMsg("Saved online. Public app will use the new content.")}catch(e){setMsg("Firebase save failed: check Firestore/Auth setup.")}setTimeout(()=>setMsg(""),3500)};
 const login=async e=>{e.preventDefault();setAuthMsg("");try{await signInWithEmailAndPassword(auth,email,password)}catch(err){setAuthMsg("Login failed. Firebase Authentication me Email/Password account create/enable karein.")}};
 const loadLeads=async()=>{setLoadingLeads(true);try{const snap=await getDocs(query(collection(db,"leads"),orderBy("createdAt","desc")));setLeads(snap.docs.map(d=>({id:d.id,...d.data()})))}catch(e){setLeads([]);setMsg("Leads read nahi ho pa rahe. Firestore rules check karein.")}setLoadingLeads(false)};
 useEffect(()=>{if(active==="leads"&&user)loadLeads()},[active,user]);
 const exportData=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="mr-sab-kuch-content.json";a.click();URL.revokeObjectURL(a.href)};
 const importData=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{setData(clone(JSON.parse(r.result)));setMsg("Imported. Click Save Online.")}catch{setMsg("Invalid JSON file")}};r.readAsText(f)};
 const serviceCount=useMemo(()=>data.services.filter(x=>x.visible).length,[data.services]);
 if(authLoading)return <div className="admin-login"><div className="login-card"><h1>Mr. Sab Kuch</h1><p>Loading admin...</p></div></div>;
 if(!user)return <div className="admin-login"><form className="login-card" onSubmit={login}><div className="login-logo">NISS</div><h1>Mr. Sab Kuch Admin</h1><p>Only authorised admin can change online content.</p><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Admin email" required/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" required/><button className="primary-btn">Login</button>{authMsg&&<div className="admin-error">{authMsg}</div>}<Link to="/" className="back-link">← Back to app</Link></form></div>;
 return <div className="msa-page"><aside className="msa-side"><div className="admin-brand"><div>MSK</div><span>Mr. Sab Kuch<small>NISS Technology</small></span></div><button className={active==="overview"?"side-active":""} onClick={()=>setActive("overview")}>📊 Overview</button><button className={active==="brand"?"side-active":""} onClick={()=>setActive("brand")}>⚙️ Website</button><button className={active==="services"?"side-active":""} onClick={()=>setActive("services")}>🧩 Services</button><button className={active==="packages"?"side-active":""} onClick={()=>setActive("packages")}>💰 Packages</button><button className={active==="offers"?"side-active":""} onClick={()=>setActive("offers")}>🎁 Offers</button><button className={active==="sections"?"side-active":""} onClick={()=>setActive("sections")}>🧱 Sections</button><button className={active==="leads"?"side-active":""} onClick={()=>setActive("leads")}>📥 Leads</button><button className={active==="backup"?"side-active":""} onClick={()=>setActive("backup")}>💾 Backup</button><Link to="/">↗ View App</Link><button onClick={()=>signOut(auth)}>↪ Logout</button></aside>
 <main className="msa-main"><div className="msa-top"><div><h1>Control Center</h1><p>Online content, services, packages and leads manage karein.</p></div><button className="primary-btn" onClick={save}>Save Online</button></div>{msg&&<div className="msa-msg">{msg}</div>}
 {active==="overview"&&<><div className="admin-cards"><div><span>Visible Services</span><strong>{serviceCount}</strong></div><div><span>Packages</span><strong>{data.packages.length}</strong></div><div><span>Offers</span><strong>{data.offers.length}</strong></div><div><span>Logged in as</span><strong className="small-value">{user.email}</strong></div></div><section className="msa-box"><h2>What is ready</h2><p>Customer app, service routing, WhatsApp/Call actions, enquiry form, online CMS, package editing, offer editing, custom sections, JSON backup and protected admin login.</p><p><b>Next deployment:</b> Firebase + Vercel/hosting. After deployment, one public URL can be shared on WhatsApp.</p></section></>}
 {active==="brand"&&<section className="msa-box"><h2>Website & Contact</h2><div className="msa-form-grid">{Object.entries(data.brand).map(([k,v])=><label key={k}><span>{k}</span>{k==="heroText"||k==="address"?<textarea value={v} onChange={e=>updateBrand(k,e.target.value)}/>:<input value={v} onChange={e=>updateBrand(k,e.target.value)}/>}</label>)}</div></section>}
 {active==="services"&&<section className="msa-box"><div className="msa-row"><h2>Services</h2><button className="secondary" onClick={()=>add("services",{id:"service-"+Date.now(),title:"New Service",icon:"✨",path:"/",description:"Edit description",visible:true})}>+ Add Service</button></div>{data.services.map(s=><div className="msa-item" key={s.id}><input className="icon" value={s.icon} onChange={e=>updateList("services",s.id,"icon",e.target.value)}/><input value={s.title} onChange={e=>updateList("services",s.id,"title",e.target.value)}/><input value={s.path} onChange={e=>updateList("services",s.id,"path",e.target.value)}/><textarea value={s.description} onChange={e=>updateList("services",s.id,"description",e.target.value)}/><label className="check"><input type="checkbox" checked={!!s.visible} onChange={e=>updateList("services",s.id,"visible",e.target.checked)}/> Show</label><button className="danger" onClick={()=>remove("services",s.id)}>Delete</button></div>)}</section>}
 {active==="packages"&&<section className="msa-box"><div className="msa-row"><h2>Packages & Pricing</h2><button className="secondary" onClick={()=>add("packages",{id:"package-"+Date.now(),name:"New Package",price:"₹0",subtitle:"Edit package",features:["Feature 1"],visible:true})}>+ Add Package</button></div>{data.packages.map(p=><div className="msa-item package" key={p.id}><input value={p.name} onChange={e=>updateList("packages",p.id,"name",e.target.value)}/><input value={p.price} onChange={e=>updateList("packages",p.id,"price",e.target.value)}/><input value={p.subtitle} onChange={e=>updateList("packages",p.id,"subtitle",e.target.value)}/><textarea value={(p.features||[]).join("\n")} onChange={e=>updateList("packages",p.id,"features",e.target.value.split("\n"))}/><label className="check"><input type="checkbox" checked={!!p.visible} onChange={e=>updateList("packages",p.id,"visible",e.target.checked)}/> Show</label><button className="danger" onClick={()=>remove("packages",p.id)}>Delete</button></div>)}</section>}
 {active==="offers"&&<section className="msa-box"><div className="msa-row"><h2>Offers / Ads</h2><button className="secondary" onClick={()=>add("offers",{id:"offer-"+Date.now(),title:"New Offer",text:"Offer text",button:"Get Started",visible:true})}>+ Add Offer</button></div>{data.offers.map(o=><div className="msa-item" key={o.id}><input value={o.title} onChange={e=>updateList("offers",o.id,"title",e.target.value)}/><textarea value={o.text} onChange={e=>updateList("offers",o.id,"text",e.target.value)}/><input value={o.button} onChange={e=>updateList("offers",o.id,"button",e.target.value)}/><label className="check"><input type="checkbox" checked={!!o.visible} onChange={e=>updateList("offers",o.id,"visible",e.target.checked)}/> Show</label><button className="danger" onClick={()=>remove("offers",o.id)}>Delete</button></div>)}</section>}
 {active==="sections"&&<section className="msa-box"><div className="msa-row"><h2>Custom Sections</h2><button className="secondary" onClick={()=>add("sections",{id:"section-"+Date.now(),title:"New Section",text:"Write content here.",visible:true})}>+ Add Section</button></div>{data.sections.map(s=><div className="msa-item section" key={s.id}><input value={s.title} onChange={e=>updateList("sections",s.id,"title",e.target.value)}/><textarea value={s.text} onChange={e=>updateList("sections",s.id,"text",e.target.value)}/><label className="check"><input type="checkbox" checked={!!s.visible} onChange={e=>updateList("sections",s.id,"visible",e.target.checked)}/> Show</label><button className="danger" onClick={()=>remove("sections",s.id)}>Delete</button></div>)}</section>}
 {active==="leads"&&<section className="msa-box"><div className="msa-row"><h2>Customer Leads</h2><button className="secondary" onClick={loadLeads}>Refresh</button></div>{loadingLeads?<p>Loading...</p>:leads.length===0?<p>No leads found yet.</p>:<div className="lead-table">{leads.map(l=><div className="lead-row" key={l.id}><b>{l.name}</b><span>{l.phone}</span><span>{l.service||"General"}</span><span>{l.message||"—"}</span><a href={`https://wa.me/${String(l.phone).replace(/\D/g,"")}`} target="_blank" rel="noreferrer">WhatsApp</a></div>)}</div>}</section>}
 {active==="backup"&&<section className="msa-box"><h2>Backup / Restore</h2><div className="msa-tools"><button className="secondary" onClick={exportData}>Export JSON</button><label className="filebtn">Import JSON<input type="file" accept="application/json" onChange={importData}/></label><button className="danger" onClick={()=>{resetCMS();setData(clone(defaultCMS));setMsg("Local cache reset. Save Online to publish defaults.")}}>Reset Default</button></div><p className="note">Public content Firestore me save hota hai. JSON backup offline copy ke liye hai.</p></section>}
 </main></div>
}
